import type { Metadata } from "next";
import "../globals.css";
import { Inter } from "next/font/google";
import Menu from "@/components/shared/Menu";
import Navbar from "@/components/shared/Navbar";
import { QueryProvider } from "@/components/scheduler/QueryProvider";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "@/components/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "School Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <head>
        <link
          rel="dx-theme"
          data-theme="fluent.blue.light"
          href="http://192.168.100.33:8080/absproxy/3000/dx.generic.custom-scheme.css"
          data-active="true"
        />
        <link
          rel="dx-theme"
          data-theme="fluent.blue.dark"
          href="http://192.168.100.33:8080/absproxy/3000/dx.fluent.blue.dark.css"
          data-active="false"
        />
      </head> */}
      <body className={`${inter.className} flex flex-row`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProvider>{children}</QueryProvider>
          <Toaster></Toaster>
        </ThemeProvider>
      </body>
    </html>
  );
}
