import "../../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { QueryProvider } from "@/components/QueryProvider";
import Menu from "@/components/shared/Menu";
import Navbar from "@/components/shared/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <QueryProvider>
          <Menu role="teacher" />
          <div className="h-full ml-[300px]">
            <Navbar />

            {children}
          </div>
        </QueryProvider>
        {/* {children} */}
      </body>
    </html>
  );
}
